#!/bin/bash

#Create files for haproxy

if [! -f /etc/haproxy/certs ]; then
	mkdir /etc/haproxy/certs
fi

if [! -f /etc/haproxy/crt-list.txt ]; then
	touch /etc/haproxy/crt-list.txt
fi

#Get certificates using data from db
for i in $( mysql -u $MYSQL_USER -p$MYSQL_PASS -h$MYSQL_HOST $MYSQL_DB -e "select blog_id from wp_blogs where archived = 0 and deleted = 0;" -N -B ); do
        #Check if active domain is set in wp_domain mapping
        if [[ $( mysql -u $MYSQL_USER -p$MYSQL_PASS -h$MYSQL_HOST $MYSQL_DB -e "SELECT blog_id FROM wp_domain_mapping WHERE active = 1 AND blog_id = $i;" -N -B) ]]; then
                sql="SELECT domain FROM wp_domain_mapping WHERE active = 1 AND blog_id = $i;"
        #Use base wp_options for network domain
        elif [ $i = 1 ]; then
                sql="SELECT option_value FROM wp_options WHERE option_name = 'home';"
        #If domain mapping isn't set up, grap domain from wp_*_options home value
        else
                sql="SELECT option_value FROM wp_"$i"_options WHERE option_name = 'home';"
        fi

        #Set var for domain
        domain=$(mysql -u $MYSQL_USER -p$MYSQL_PASS -h$MYSQL_HOST $MYSQL_DB -e "$sql" -B -N)

        #Strip scheme from domain value
        domain=$(bash -c "echo $domain | sed -r 's/^https?:\/\///; s/\/$//'")

        #set path for where the combined certificate and key will be created
        combined_file="/etc/haproxy/certs/${domain}.pem"

        #if certificate already exists don't get a new one.
        if [ -a $combined_file ]; then
                echo "combined file already exists $combined_file"
        else
                #get certificate including www version
                certbot-auto certonly --standalone --preferred-challenges http-01 --http-01-port 54321 -d $domain -d "www.$domain"

                #create combined certificate and key for haproxy
                bash -c "cat /etc/letsencrypt/live/$domain/fullchain.pem /etc/letsencrypt/live/$domain/privkey.pem > $combined_file"

                #add to cert list so haproxy knows which certs to use for which domains
                echo "$combined_file $domain www.$domain" >> /etc/haproxy/crt-list.txt
        fi
done
